name: Monitor pagine

on:
  schedule:
    - cron: '0 */3 * * *'       # alle 00, 03, 06… UTC
  workflow_dispatch:            # avvio manuale

jobs:
  check:
    runs-on: ubuntu-latest
    permissions: write-all       # permette al bot di fare commit

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run monitor script
        run: python check.py
        env:
          SMTP_HOST:  ${{ secrets.SMTP_HOST }}
          SMTP_PORT:  ${{ secrets.SMTP_PORT }}
          SMTP_USER:  ${{ secrets.SMTP_USER }}
          SMTP_PASS:  ${{ secrets.SMTP_PASS }}
          MAIL_FROM:  ${{ secrets.MAIL_FROM }}
          MAIL_TO:    ${{ secrets.MAIL_TO }}

      - name: Commit updated hashes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'hashes.json'
          author_name: monitor-bot
          message: 'update hashes [skip ci]'
